# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BtCKy7Yyl3K-HUqRLJuHGQB1iAbtcfMc
"""

pip install streamlit openai

import streamlit as st
from openai import OpenAI
client = OpenAI(api_key="YOUR_API_KEY")
def ask_ai(prompt):
  response = client.chat.completions.create(
model="gpt-4o-mini",
messages=[{"role": "user", "content": prompt}],
temperature=0.7
)
  return response.choices[0].message.content
st.set_page_config(page_title="AI Smart Academic Assistant",
layout="wide")
st.title("🎓 AI Smart Academic Assistant")
st.markdown("Uses Multiple Prompt Engineering Techniques")
option = st.sidebar.selectbox(
"Select Module",
[
"Text Summarization (Zero-Shot)",
"Sentiment Analysis (Few-Shot)",
"Concept Explanation (Role-Based)",
"Data Preprocessing Advice (Context-Based)",
"Math Problem Solver (Chain-of-Thought)",
"Structured Notes Generator",
"Concept Comparison",
"Language Translation",
"Refinement Mode"
]
)

if option == "Text Summarization (Zero-Shot)":
  st.header("📄 Text Summarization")
  text = st.text_area("Enter text to summarize:")
  if st.button("Summarize"):
    prompt = f"Summarize the following text in 100 words:\n\n{text}"
    output = ask_ai(prompt)
    st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")
elif option == "Sentiment Analysis (Few-Shot)":
  st.header("😊 Sentiment Analysis")
  text = st.text_area("Enter feedback text:")
  if st.button("Analyze"):
    prompt = f"""
Text: The teaching was excellent.
Sentiment: Positive
Text: The syllabus is too lengthy.
Sentiment: Negative
Text: {text}
Sentiment:
"""
  output = ask_ai(prompt)
  st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Concept Explanation (Role-Based)":
    st.header("👨🏫 Concept Explanation")

    topic = st.text_input("Enter topic:")

    if st.button("Explain"):
        prompt = f"Act as a Professor. Explain {topic} with a real-life example."
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Data Preprocessing Advice (Context-Based)":
    st.header("📊 Data Preprocessing Advice")

    context = st.text_area("Describe dataset issue:")

    if st.button("Get Suggestions"):
        prompt = f"""
Context:
{context}

Task:
Suggest suitable preprocessing techniques.
"""
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Math Problem Solver (Chain-of-Thought)":
    st.header("🧮 Math Problem Solver")

    problem = st.text_area("Enter math problem:")

    if st.button("Solve"):
        prompt = f"{problem}\nExplain step by step."
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Structured Notes Generator":
    st.header("📝 Structured Notes")

    topic = st.text_input("Enter topic:")

    if st.button("Generate Notes"):
        prompt = f"""
Explain {topic}.

Provide output in:
1. Definition
2. Advantages
3. Disadvantages
4. Applications
"""
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Concept Comparison":
    st.header("🧮 Concept Comparison")

    concept1 = st.text_input("Concept 1:")
    concept2 = st.text_input("Concept 2:")

    if st.button("Compare"):
        prompt = f"""
Compare {concept1} and {concept2}.
Present differences in table format.
"""
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Language Translation":
    st.header("🌍 Language Translation")

    text = st.text_area("Enter text:")
    language = st.text_input("Translate to which language?")

    if st.button("Translate"):
        prompt = f"Translate the following text into {language}:\n{text}"
        output = ask_ai(prompt)
        st.success(output)

if option == "Chatbot":
    st.header("🤖 Chatbot")

elif option == "Refinement Mode":
    st.header("🔁 Refinement Mode")

    text = st.text_area("Enter content:")
    refinement = st.text_input("How should it be refined? (e.g., shorter, technical, simple)")

    if st.button("Refine"):
        prompt = f"{text}\n\nNow make it {refinement}."
        output = ask_ai(prompt)
        st.success(output)

